services:
  postgres:
    image: postgres:18.4
    container_name: project_name-postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: db_user_name
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
    volumes:
      - name_here_postgres_data:/var/lib/postgresql

volumes:
  requestops_postgres_data:
