services:
  postgres:
    image: postgres:18.4
    container_name: github-issue-hunter-postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - github_issue_hunter_postgres_data:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  github_issue_hunter_postgres_data:
